'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
   return queryInterface.bulkInsert('Events', [
     {
        groupId: 1,
        eventDetails: 'Lining up for BJs',
        eventImage: 'image1.jpg',
        location: 'BJs Restaurant & Brewhouse in Clearwater, FL',
        price: 50,
        dateAndTime: new Date(),
        phoneNumber: 1002200114,
        createdAt: new Date(),
        updatedAt: new Date(),
     },
     {
      groupId: 3,
      eventDetails: 'Who Wanna have fun at Thai Nana?',
      eventImage: 'image1.jpg',
      location: 'Thai Nana Restaurant Palm Harbor, FL',
      price: 65,
      dateAndTime: new Date(),
      phoneNumber: 1002200115,
      createdAt: new Date(),
      updatedAt: new Date(),
     },
     {
      groupId: 2,
      eventDetails: 'All you can Chew at the Churrascaria!',
      eventImage: 'image1.jpg',
      location: 'Terra Guacha Brazilian Steakhouse Tampa, FL',
      price: 100,
      dateAndTime: new Date(),
      phoneNumber: 1002200116,
      createdAt: new Date(),
      updatedAt: new Date(),
     },
     {
      groupId: 7,
      eventDetails: 'Packing in at Packards',
      eventImage: 'image1.jpg',
      location: 'Packards Steak House Palm Harbor, FL',
      price: 75,
      dateAndTime: new Date(),
      phoneNumber: 1002200166,
      createdAt: new Date(),
      updatedAt: new Date(),
     },
     {
      groupId: 10,
      eventDetails: 'Time to Grit and Bear it!',
      eventImage: 'image1.jpg',
      location: 'Johnny Grits Tarpon Springs, FL',
      price: 30,
      dateAndTime: new Date(),
      phoneNumber: 1002200156,
      createdAt: new Date(),
      updatedAt: new Date(),
     },
     {
      groupId: 6,
      eventDetails: 'Discovering India',
      eventImage: 'image1.jpg',
      location: 'Discovery Indian Cuisine Palm Harbor, FL',
      price: 75,
      dateAndTime: new Date(),
      phoneNumber: 1002200146,
      createdAt: new Date(),
      updatedAt: new Date(),
     },
     {
      groupId: 5,
      eventDetails: 'Grilling Salamanders?',
      eventImage: 'image1.jpg',
      location: 'Market Salamander Grille Palm Harbor, FL',
      price: 90,
      dateAndTime: new Date(),
      phoneNumber: 1002200136,
      createdAt: new Date(),
      updatedAt: new Date(),
     },
     {
      groupId: 4,
      eventDetails: 'Filling Bellies at the Waterfront',
      eventImage: 'image1.jpg',
      location: 'Rusty Bellies Waterfront Grill Tarpon Springs, FL',
      price: 80,
      dateAndTime: new Date(),
      phoneNumber: 1002200126,
      createdAt: new Date(),
      updatedAt: new Date(),
     },
     {
      groupId: 9,
      eventDetails: 'Raiding Jacks Table!',
      eventImage: 'image1.jpg',
      location: 'Captain Jacks Waterfront Grille Tarpon Springs, FL',
      price: 90,
      dateAndTime: new Date(),
      phoneNumber: 1002200106,
      createdAt: new Date(),
      updatedAt: new Date(),
     },
     {
      groupId: 8,
      eventDetails: 'Saki and Hibachi with Friends',
      eventImage: 'image1.jpg',
      location: 'Saki Endless Sushi & Hibachi Palm Harbor, FL',
      price: 85,
      dateAndTime: new Date(),
      phoneNumber: 1002200906,
      createdAt: new Date(),
      updatedAt: new Date(),
     },
  ], {});
    
  },

  down: async (queryInterface, Sequelize) => {
    return await queryInterface.bulkDelete('Events', null, {});
    
  }
};
